# Generated by Django 3.1.7 on 2021-04-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('phno', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('doj', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('leaveid', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leaves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(blank=True, max_length=225, null=True)),
                ('basic', models.IntegerField(blank=True, null=True)),
                ('houserentallowance', models.IntegerField(blank=True, null=True)),
                ('pf', models.IntegerField(blank=True, null=True)),
                ('bonus', models.IntegerField(blank=True, null=True)),
                ('travelallowance', models.IntegerField(blank=True, null=True)),
                ('medicalallowance', models.IntegerField(blank=True, null=True)),
                ('pfcontribution', models.IntegerField(blank=True, null=True)),
                ('welfaretrust', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('isadmin', models.IntegerField(blank=True, db_column='isAdmin', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accountdetails',
            fields=[
                ('empid', models.OneToOneField(db_column='empid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='view.employee')),
                ('bankaccountno', models.CharField(max_length=45)),
                ('pan_no', models.CharField(blank=True, db_column='pan no', max_length=45, null=True)),
                ('pf_number', models.CharField(blank=True, db_column='pf number', max_length=45, null=True)),
            ],
            options={
                'db_table': 'accountdetails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emprole',
            fields=[
                ('empid', models.OneToOneField(db_column='empid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='view.employee')),
                ('joblocation', models.CharField(blank=True, max_length=45, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emprole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='view.employee')),
                ('query', models.CharField(max_length=225)),
                ('qdate', models.DateField()),
                ('status', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'queries',
                'managed': False,
            },
        ),
    ]
